// <auto-generated />
namespace HedgeHogOtter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CertainBookValuesRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CertainBookValuesRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201612072220252_Certain Book Values Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
