//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeHogOtter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string Title { get; set; }
        public string ISBN { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Subject { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public string BookCondition { get; set; }
        public string PublisherPlace { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Id { get; set; }

        public Nullable <int> FeatureFlag { get; set; }


    }
}
